language: python
python:
    - "3.4"
    - "3.5"

env:
    - TEST_DIR=lets_build_a_interpreter

script:
    - cd $TEST_DIR && pip install . && pip install -r tests_require && python -m pytest tests/*
